version: "3.9" 

services:
  nextjs: 
    build: ./

  nginx: 
    image: nginx:1.21.4-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX}:80"

